application: crowd-sourcing-report
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries: 
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: matplotlib
  version: latest
- name: pycrypto
  version: latest


handlers:
- url: /Content/js
  static_dir: Content/js
- url: /Content/fonts
  static_dir: Content/fonts
- url: /Content/css
  static_dir: Content/css
- url: /Content/carousal
  static_dir: Content/carousal
- url: /Content/img
  static_dir: Content/img
- url: /propose
  script: propose.app
- url: /propose/.*
  script: propose.app
- url: /signup/.*
  script: signup.app
- url: /home
  script: home.app
- url: /home/.*
  script: home.app
- url: /admin
  script: admin.app
- url: /admin/.*
  script: admin.app
- url: /.*
  script: main.app

